---
name: Deploy to RubyGems
on:
  workflow_dispatch:
    inputs:
      do_deploy:
        description: "Should we deploy to RubyGems?"
        required: true
      ignore_version_check:
        description: "Should we ignore version checks during this run?"
        required: false
        default: no
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Stop the deploy if do_deploy is not set to true"
        if: github.event.inputs.do_deploy != 'true'
        uses: andymckay/cancel-action@0.2
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Ensure that the VERSION file has been updated.
        if: github.event.inputs.ignore_version_check != 'yes'
        run: make ensure_version
      - name: Deploy to RubyGems
        run: make deploy
