---
name: Run tests
on:
  pull_request:
    branches:
      - master
  push:
    paths-ignore:
      - "README.md"
      - 'content/**'

jobs:
  stop_if_tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Cancel if this workflow was invokved by a new tag
        uses: andymckay/cancel-action@0.2
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Run unit tests
        run: make test
  # Our integration tests require Vagrant and VirtualBox.
  # Only the MacOS builders supported VT-x, which is required by VirtualBox.
  integration:
    needs: unit
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Install Ansible
        run: brew install ansible
      # Vagrant is super flaky on these runners.
      - name: Run integration tests
        run: make integration
      - name: Execute deployment if integration tests successful and we're on master.
        if: success() && github.ref == 'refs/heads/master'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to RubyGems
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "do_deploy": "true" }'
